import type { Metadata } from "next";
import { Check } from "lucide-react";

import { CalendlyEmbed } from "@/components/schedule/CalendlyEmbed";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { env } from "@/env";

const checklist = [
  "Deep dive on your customer journeys",
  "Map of the first two digital employees",
  "Timeline, investment, and operators assigned",
];

export const metadata: Metadata = {
  title: "Book — First Class AI",
  description:
    "Schedule your build briefing with First Class AI to align on priorities, outcomes, and deployment plan.",
};

export default function BookPage() {
  const calendlyUrl =
    env.CALENDLY_SCHEDULING_URL ??
    "https://calendly.com/first-class-ai/build-briefing";

  return (
    <div className="grid gap-12 md:grid-cols-[minmax(0,0.85fr)_minmax(0,1fr)] md:items-start">
      <Card className="h-full border-border/70 bg-white">
        <CardHeader>
          <CardTitle className="text-2xl font-semibold tracking-tight">
            Here’s what happens next
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-5 text-sm text-muted-foreground">
          <p>
            Book your build briefing. It’s a 30-minute working session with our operators
            and automation architects. We walk you through the blueprint and confirm the
            ROI targets together.
          </p>
          <ul className="space-y-3">
            {checklist.map((item) => (
              <li key={item} className="flex items-start gap-3">
                <Check className="mt-1 h-4 w-4 text-foreground" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p className="rounded-2xl border border-border px-4 py-3 text-xs uppercase tracking-[0.2em] text-muted-foreground">
            Zoom link is auto-generated by Calendly once you confirm
          </p>
        </CardContent>
      </Card>
      <CalendlyEmbed url={calendlyUrl} />
    </div>
  );
}
